/* Auto-generated by genmsg_cpp for file /home/administrator/myros/drh-robotics-ros/79/ros/ardros/srv/SetDriveControlGains.srv */
#ifndef ARDROS_SERVICE_SETDRIVECONTROLGAINS_H
#define ARDROS_SERVICE_SETDRIVECONTROLGAINS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace ardros
{
template <class ContainerAllocator>
struct SetDriveControlGainsRequest_ {
  typedef SetDriveControlGainsRequest_<ContainerAllocator> Type;

  SetDriveControlGainsRequest_()
  : velocityPParam(0.0)
  , velocityIParam(0.0)
  , turnPParam(0.0)
  , turnIParam(0.0)
  {
  }

  SetDriveControlGainsRequest_(const ContainerAllocator& _alloc)
  : velocityPParam(0.0)
  , velocityIParam(0.0)
  , turnPParam(0.0)
  , turnIParam(0.0)
  {
  }

  typedef float _velocityPParam_type;
  float velocityPParam;

  typedef float _velocityIParam_type;
  float velocityIParam;

  typedef float _turnPParam_type;
  float turnPParam;

  typedef float _turnIParam_type;
  float turnIParam;


  typedef boost::shared_ptr< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetDriveControlGainsRequest
typedef  ::ardros::SetDriveControlGainsRequest_<std::allocator<void> > SetDriveControlGainsRequest;

typedef boost::shared_ptr< ::ardros::SetDriveControlGainsRequest> SetDriveControlGainsRequestPtr;
typedef boost::shared_ptr< ::ardros::SetDriveControlGainsRequest const> SetDriveControlGainsRequestConstPtr;


template <class ContainerAllocator>
struct SetDriveControlGainsResponse_ {
  typedef SetDriveControlGainsResponse_<ContainerAllocator> Type;

  SetDriveControlGainsResponse_()
  {
  }

  SetDriveControlGainsResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SetDriveControlGainsResponse
typedef  ::ardros::SetDriveControlGainsResponse_<std::allocator<void> > SetDriveControlGainsResponse;

typedef boost::shared_ptr< ::ardros::SetDriveControlGainsResponse> SetDriveControlGainsResponsePtr;
typedef boost::shared_ptr< ::ardros::SetDriveControlGainsResponse const> SetDriveControlGainsResponseConstPtr;

struct SetDriveControlGains
{

typedef SetDriveControlGainsRequest Request;
typedef SetDriveControlGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct SetDriveControlGains
} // namespace ardros

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ef02095d661072b02e76d2e1f6bddf8";
  }

  static const char* value(const  ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7ef02095d661072bULL;
  static const uint64_t static_value2 = 0x02e76d2e1f6bddf8ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ardros/SetDriveControlGainsRequest";
  }

  static const char* value(const  ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 velocityPParam\n\
float32 velocityIParam\n\
float32 turnPParam\n\
float32 turnIParam\n\
\n\
";
  }

  static const char* value(const  ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ardros/SetDriveControlGainsResponse";
  }

  static const char* value(const  ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ardros::SetDriveControlGainsRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.velocityPParam);
    stream.next(m.velocityIParam);
    stream.next(m.turnPParam);
    stream.next(m.turnIParam);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetDriveControlGainsRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ardros::SetDriveControlGainsResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SetDriveControlGainsResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<ardros::SetDriveControlGains> {
  static const char* value() 
  {
    return "7ef02095d661072b02e76d2e1f6bddf8";
  }

  static const char* value(const ardros::SetDriveControlGains&) { return value(); } 
};

template<>
struct DataType<ardros::SetDriveControlGains> {
  static const char* value() 
  {
    return "ardros/SetDriveControlGains";
  }

  static const char* value(const ardros::SetDriveControlGains&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ardros::SetDriveControlGainsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ef02095d661072b02e76d2e1f6bddf8";
  }

  static const char* value(const ardros::SetDriveControlGainsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ardros::SetDriveControlGainsRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ardros/SetDriveControlGains";
  }

  static const char* value(const ardros::SetDriveControlGainsRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ardros::SetDriveControlGainsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7ef02095d661072b02e76d2e1f6bddf8";
  }

  static const char* value(const ardros::SetDriveControlGainsResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ardros::SetDriveControlGainsResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ardros/SetDriveControlGains";
  }

  static const char* value(const ardros::SetDriveControlGainsResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ARDROS_SERVICE_SETDRIVECONTROLGAINS_H

